// WARNING: THIS IS AN AUTOGENERATED FILE. DO NOT DIRECTLY EDIT.
const ImagesMeta = {
	Brothers: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Brothers_100w_100h.png'
			},
			{
				width: 200,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Brothers_200w_200h.png'
			},
			{
				width: 300,
				height: 300,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Brothers_300w_300h.png'
			},
			{
				width: 400,
				height: 400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Brothers_400w_400h.png'
			},
			{
				width: 500,
				height: 500,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Brothers_500w_500h.png'
			},
			{
				width: 600,
				height: 600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Brothers_600w_600h.png'
			}
		]
	},
	Stream: {
		ext: 'jpg',
		sizes: [
			{
				width: 100,
				height: 66,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_100w_66h.jpg'
			},
			{
				width: 200,
				height: 133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_200w_133h.jpg'
			},
			{
				width: 300,
				height: 199,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_300w_199h.jpg'
			},
			{
				width: 400,
				height: 266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_400w_266h.jpg'
			},
			{
				width: 500,
				height: 333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_500w_333h.jpg'
			},
			{
				width: 600,
				height: 399,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_600w_399h.jpg'
			},
			{
				width: 700,
				height: 466,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_700w_466h.jpg'
			},
			{
				width: 800,
				height: 533,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_800w_533h.jpg'
			},
			{
				width: 900,
				height: 599,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_900w_599h.jpg'
			},
			{
				width: 1000,
				height: 666,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1000w_666h.jpg'
			},
			{
				width: 1100,
				height: 733,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1100w_733h.jpg'
			},
			{
				width: 1200,
				height: 799,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1200w_799h.jpg'
			},
			{
				width: 1300,
				height: 866,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1300w_866h.jpg'
			},
			{
				width: 1400,
				height: 933,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1400w_933h.jpg'
			},
			{
				width: 1500,
				height: 999,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1500w_999h.jpg'
			},
			{
				width: 1600,
				height: 1066,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1600w_1066h.jpg'
			},
			{
				width: 1700,
				height: 1133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1700w_1133h.jpg'
			},
			{
				width: 1800,
				height: 1199,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1800w_1199h.jpg'
			},
			{
				width: 1900,
				height: 1266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_1900w_1266h.jpg'
			},
			{
				width: 2000,
				height: 1333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_2000w_1333h.jpg'
			},
			{
				width: 2048,
				height: 1365,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Stream_2048w_1365h.jpg'
			}
		]
	},
	Socials: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Socials_100w_100h.png'
			},
			{
				width: 200,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Socials_200w_200h.png'
			},
			{
				width: 300,
				height: 300,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Socials_300w_300h.png'
			},
			{
				width: 400,
				height: 400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Socials_400w_400h.png'
			},
			{
				width: 500,
				height: 500,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Socials_500w_500h.png'
			},
			{
				width: 600,
				height: 600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Socials_600w_600h.png'
			}
		]
	},
	ApoNCDiaperBank: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 78,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_100w_78h.png'
			},
			{
				width: 200,
				height: 157,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_200w_157h.png'
			},
			{
				width: 300,
				height: 235,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_300w_235h.png'
			},
			{
				width: 400,
				height: 314,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_400w_314h.png'
			},
			{
				width: 500,
				height: 392,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_500w_392h.png'
			},
			{
				width: 600,
				height: 471,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_600w_471h.png'
			},
			{
				width: 700,
				height: 550,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_700w_550h.png'
			},
			{
				width: 800,
				height: 628,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_800w_628h.png'
			},
			{
				width: 900,
				height: 707,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_900w_707h.png'
			},
			{
				width: 1000,
				height: 785,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1000w_785h.png'
			},
			{
				width: 1100,
				height: 864,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1100w_864h.png'
			},
			{
				width: 1200,
				height: 943,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1200w_943h.png'
			},
			{
				width: 1300,
				height: 1021,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1300w_1021h.png'
			},
			{
				width: 1400,
				height: 1100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1400w_1100h.png'
			},
			{
				width: 1500,
				height: 1178,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1500w_1178h.png'
			},
			{
				width: 1600,
				height: 1257,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1600w_1257h.png'
			},
			{
				width: 1700,
				height: 1335,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1700w_1335h.png'
			},
			{
				width: 1800,
				height: 1414,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1800w_1414h.png'
			},
			{
				width: 1900,
				height: 1493,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_1900w_1493h.png'
			},
			{
				width: 2000,
				height: 1571,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_2000w_1571h.png'
			},
			{
				width: 2064,
				height: 1622,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoNCDiaperBank_2064w_1622h.png'
			}
		]
	},
	DukeApoBanner: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 29,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_100w_29h.png'
			},
			{
				width: 200,
				height: 58,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_200w_58h.png'
			},
			{
				width: 300,
				height: 87,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_300w_87h.png'
			},
			{
				width: 400,
				height: 117,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_400w_117h.png'
			},
			{
				width: 500,
				height: 146,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_500w_146h.png'
			},
			{
				width: 600,
				height: 175,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_600w_175h.png'
			},
			{
				width: 700,
				height: 204,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_700w_204h.png'
			},
			{
				width: 800,
				height: 234,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_800w_234h.png'
			},
			{
				width: 900,
				height: 263,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_900w_263h.png'
			},
			{
				width: 1000,
				height: 292,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1000w_292h.png'
			},
			{
				width: 1100,
				height: 322,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1100w_322h.png'
			},
			{
				width: 1200,
				height: 351,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1200w_351h.png'
			},
			{
				width: 1300,
				height: 380,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1300w_380h.png'
			},
			{
				width: 1400,
				height: 409,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1400w_409h.png'
			},
			{
				width: 1500,
				height: 439,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1500w_439h.png'
			},
			{
				width: 1600,
				height: 468,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1600w_468h.png'
			},
			{
				width: 1700,
				height: 497,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1700w_497h.png'
			},
			{
				width: 1800,
				height: 526,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1800w_526h.png'
			},
			{
				width: 1900,
				height: 556,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_1900w_556h.png'
			},
			{
				width: 2000,
				height: 585,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_2000w_585h.png'
			},
			{
				width: 2046,
				height: 599,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoBanner_2046w_599h.png'
			}
		]
	},
	ApoClock: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoClock_100w_100h.png'
			},
			{
				width: 200,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoClock_200w_200h.png'
			},
			{
				width: 300,
				height: 300,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoClock_300w_300h.png'
			},
			{
				width: 400,
				height: 400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoClock_400w_400h.png'
			},
			{
				width: 500,
				height: 500,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoClock_500w_500h.png'
			},
			{
				width: 600,
				height: 600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/ApoClock_600w_600h.png'
			}
		]
	},
	DukeApoLogoBlack: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 32,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoLogoBlack_100w_32h.png'
			},
			{
				width: 200,
				height: 64,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoLogoBlack_200w_64h.png'
			},
			{
				width: 300,
				height: 96,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoLogoBlack_300w_96h.png'
			},
			{
				width: 393,
				height: 126,
				url: 'https://storage.googleapis.com/dukeapo-static-images/DukeApoLogoBlack_393w_126h.png'
			}
		]
	},
	Couch: {
		ext: 'jpg',
		sizes: [
			{
				width: 100,
				height: 66,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_100w_66h.jpg'
			},
			{
				width: 200,
				height: 133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_200w_133h.jpg'
			},
			{
				width: 300,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_300w_200h.jpg'
			},
			{
				width: 400,
				height: 266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_400w_266h.jpg'
			},
			{
				width: 500,
				height: 333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_500w_333h.jpg'
			},
			{
				width: 600,
				height: 400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_600w_400h.jpg'
			},
			{
				width: 700,
				height: 466,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_700w_466h.jpg'
			},
			{
				width: 800,
				height: 533,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_800w_533h.jpg'
			},
			{
				width: 900,
				height: 600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_900w_600h.jpg'
			},
			{
				width: 1000,
				height: 666,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1000w_666h.jpg'
			},
			{
				width: 1100,
				height: 733,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1100w_733h.jpg'
			},
			{
				width: 1200,
				height: 800,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1200w_800h.jpg'
			},
			{
				width: 1300,
				height: 866,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1300w_866h.jpg'
			},
			{
				width: 1400,
				height: 933,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1400w_933h.jpg'
			},
			{
				width: 1500,
				height: 1000,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1500w_1000h.jpg'
			},
			{
				width: 1600,
				height: 1066,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1600w_1066h.jpg'
			},
			{
				width: 1700,
				height: 1133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1700w_1133h.jpg'
			},
			{
				width: 1800,
				height: 1200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1800w_1200h.jpg'
			},
			{
				width: 1900,
				height: 1266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_1900w_1266h.jpg'
			},
			{
				width: 2000,
				height: 1333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2000w_1333h.jpg'
			},
			{
				width: 2100,
				height: 1400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2100w_1400h.jpg'
			},
			{
				width: 2200,
				height: 1466,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2200w_1466h.jpg'
			},
			{
				width: 2300,
				height: 1533,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2300w_1533h.jpg'
			},
			{
				width: 2400,
				height: 1600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2400w_1600h.jpg'
			},
			{
				width: 2500,
				height: 1666,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2500w_1666h.jpg'
			},
			{
				width: 2600,
				height: 1733,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2600w_1733h.jpg'
			},
			{
				width: 2700,
				height: 1800,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2700w_1800h.jpg'
			},
			{
				width: 2800,
				height: 1866,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2800w_1866h.jpg'
			},
			{
				width: 2900,
				height: 1933,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_2900w_1933h.jpg'
			},
			{
				width: 3000,
				height: 2000,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3000w_2000h.jpg'
			},
			{
				width: 3100,
				height: 2066,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3100w_2066h.jpg'
			},
			{
				width: 3200,
				height: 2133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3200w_2133h.jpg'
			},
			{
				width: 3300,
				height: 2200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3300w_2200h.jpg'
			},
			{
				width: 3400,
				height: 2266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3400w_2266h.jpg'
			},
			{
				width: 3500,
				height: 2333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3500w_2333h.jpg'
			},
			{
				width: 3600,
				height: 2400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3600w_2400h.jpg'
			},
			{
				width: 3700,
				height: 2466,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3700w_2466h.jpg'
			},
			{
				width: 3800,
				height: 2533,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3800w_2533h.jpg'
			},
			{
				width: 3900,
				height: 2600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_3900w_2600h.jpg'
			},
			{
				width: 4000,
				height: 2666,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4000w_2666h.jpg'
			},
			{
				width: 4100,
				height: 2733,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4100w_2733h.jpg'
			},
			{
				width: 4200,
				height: 2800,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4200w_2800h.jpg'
			},
			{
				width: 4300,
				height: 2866,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4300w_2866h.jpg'
			},
			{
				width: 4400,
				height: 2933,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4400w_2933h.jpg'
			},
			{
				width: 4500,
				height: 3000,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4500w_3000h.jpg'
			},
			{
				width: 4600,
				height: 3066,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4600w_3066h.jpg'
			},
			{
				width: 4700,
				height: 3133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4700w_3133h.jpg'
			},
			{
				width: 4800,
				height: 3200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4800w_3200h.jpg'
			},
			{
				width: 4900,
				height: 3266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_4900w_3266h.jpg'
			},
			{
				width: 5000,
				height: 3333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_5000w_3333h.jpg'
			},
			{
				width: 5100,
				height: 3400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_5100w_3400h.jpg'
			},
			{
				width: 5184,
				height: 3456,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Couch_5184w_3456h.jpg'
			}
		]
	},
	SemiFall16: {
		ext: 'jpg',
		sizes: [
			{
				width: 100,
				height: 66,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_100w_66h.jpg'
			},
			{
				width: 200,
				height: 133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_200w_133h.jpg'
			},
			{
				width: 300,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_300w_200h.jpg'
			},
			{
				width: 400,
				height: 266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_400w_266h.jpg'
			},
			{
				width: 500,
				height: 333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_500w_333h.jpg'
			},
			{
				width: 600,
				height: 400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_600w_400h.jpg'
			},
			{
				width: 700,
				height: 466,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_700w_466h.jpg'
			},
			{
				width: 800,
				height: 533,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_800w_533h.jpg'
			},
			{
				width: 900,
				height: 600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_900w_600h.jpg'
			},
			{
				width: 1000,
				height: 666,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1000w_666h.jpg'
			},
			{
				width: 1100,
				height: 733,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1100w_733h.jpg'
			},
			{
				width: 1200,
				height: 800,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1200w_800h.jpg'
			},
			{
				width: 1300,
				height: 866,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1300w_866h.jpg'
			},
			{
				width: 1400,
				height: 933,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1400w_933h.jpg'
			},
			{
				width: 1500,
				height: 1000,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1500w_1000h.jpg'
			},
			{
				width: 1600,
				height: 1066,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1600w_1066h.jpg'
			},
			{
				width: 1700,
				height: 1133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1700w_1133h.jpg'
			},
			{
				width: 1800,
				height: 1200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1800w_1200h.jpg'
			},
			{
				width: 1900,
				height: 1266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_1900w_1266h.jpg'
			},
			{
				width: 2000,
				height: 1333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2000w_1333h.jpg'
			},
			{
				width: 2100,
				height: 1400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2100w_1400h.jpg'
			},
			{
				width: 2200,
				height: 1466,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2200w_1466h.jpg'
			},
			{
				width: 2300,
				height: 1533,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2300w_1533h.jpg'
			},
			{
				width: 2400,
				height: 1600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2400w_1600h.jpg'
			},
			{
				width: 2500,
				height: 1666,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2500w_1666h.jpg'
			},
			{
				width: 2600,
				height: 1733,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2600w_1733h.jpg'
			},
			{
				width: 2700,
				height: 1800,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2700w_1800h.jpg'
			},
			{
				width: 2800,
				height: 1866,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2800w_1866h.jpg'
			},
			{
				width: 2900,
				height: 1933,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_2900w_1933h.jpg'
			},
			{
				width: 3000,
				height: 2000,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3000w_2000h.jpg'
			},
			{
				width: 3100,
				height: 2066,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3100w_2066h.jpg'
			},
			{
				width: 3200,
				height: 2133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3200w_2133h.jpg'
			},
			{
				width: 3300,
				height: 2200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3300w_2200h.jpg'
			},
			{
				width: 3400,
				height: 2266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3400w_2266h.jpg'
			},
			{
				width: 3500,
				height: 2333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3500w_2333h.jpg'
			},
			{
				width: 3600,
				height: 2400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3600w_2400h.jpg'
			},
			{
				width: 3700,
				height: 2466,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3700w_2466h.jpg'
			},
			{
				width: 3800,
				height: 2533,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3800w_2533h.jpg'
			},
			{
				width: 3900,
				height: 2600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_3900w_2600h.jpg'
			},
			{
				width: 4000,
				height: 2666,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4000w_2666h.jpg'
			},
			{
				width: 4100,
				height: 2733,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4100w_2733h.jpg'
			},
			{
				width: 4200,
				height: 2800,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4200w_2800h.jpg'
			},
			{
				width: 4300,
				height: 2866,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4300w_2866h.jpg'
			},
			{
				width: 4400,
				height: 2933,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4400w_2933h.jpg'
			},
			{
				width: 4500,
				height: 3000,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4500w_3000h.jpg'
			},
			{
				width: 4600,
				height: 3066,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4600w_3066h.jpg'
			},
			{
				width: 4700,
				height: 3133,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4700w_3133h.jpg'
			},
			{
				width: 4800,
				height: 3200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4800w_3200h.jpg'
			},
			{
				width: 4900,
				height: 3266,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_4900w_3266h.jpg'
			},
			{
				width: 5000,
				height: 3333,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_5000w_3333h.jpg'
			},
			{
				width: 5100,
				height: 3400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_5100w_3400h.jpg'
			},
			{
				width: 5184,
				height: 3456,
				url: 'https://storage.googleapis.com/dukeapo-static-images/SemiFall16_5184w_3456h.jpg'
			}
		]
	},
	Books: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Books_100w_100h.png'
			},
			{
				width: 200,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Books_200w_200h.png'
			},
			{
				width: 300,
				height: 300,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Books_300w_300h.png'
			},
			{
				width: 400,
				height: 400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Books_400w_400h.png'
			},
			{
				width: 500,
				height: 500,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Books_500w_500h.png'
			},
			{
				width: 600,
				height: 600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Books_600w_600h.png'
			}
		]
	},
	Facebook: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Facebook_100w_100h.png'
			},
			{
				width: 200,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Facebook_200w_200h.png'
			},
			{
				width: 300,
				height: 300,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Facebook_300w_300h.png'
			},
			{
				width: 352,
				height: 352,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Facebook_352w_352h.png'
			}
		]
	},
	Pledges: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Pledges_100w_100h.png'
			},
			{
				width: 200,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Pledges_200w_200h.png'
			},
			{
				width: 300,
				height: 300,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Pledges_300w_300h.png'
			},
			{
				width: 400,
				height: 400,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Pledges_400w_400h.png'
			},
			{
				width: 500,
				height: 500,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Pledges_500w_500h.png'
			},
			{
				width: 600,
				height: 600,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Pledges_600w_600h.png'
			}
		]
	},
	Broomball: {
		ext: 'jpg',
		sizes: [
			{
				width: 100,
				height: 56,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_100w_56h.jpg'
			},
			{
				width: 200,
				height: 113,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_200w_113h.jpg'
			},
			{
				width: 300,
				height: 170,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_300w_170h.jpg'
			},
			{
				width: 400,
				height: 227,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_400w_227h.jpg'
			},
			{
				width: 500,
				height: 283,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_500w_283h.jpg'
			},
			{
				width: 600,
				height: 340,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_600w_340h.jpg'
			},
			{
				width: 700,
				height: 397,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_700w_397h.jpg'
			},
			{
				width: 800,
				height: 454,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_800w_454h.jpg'
			},
			{
				width: 900,
				height: 511,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_900w_511h.jpg'
			},
			{
				width: 1000,
				height: 567,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1000w_567h.jpg'
			},
			{
				width: 1100,
				height: 624,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1100w_624h.jpg'
			},
			{
				width: 1200,
				height: 681,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1200w_681h.jpg'
			},
			{
				width: 1300,
				height: 738,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1300w_738h.jpg'
			},
			{
				width: 1400,
				height: 795,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1400w_795h.jpg'
			},
			{
				width: 1500,
				height: 851,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1500w_851h.jpg'
			},
			{
				width: 1600,
				height: 908,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1600w_908h.jpg'
			},
			{
				width: 1700,
				height: 965,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1700w_965h.jpg'
			},
			{
				width: 1800,
				height: 1022,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1800w_1022h.jpg'
			},
			{
				width: 1900,
				height: 1078,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_1900w_1078h.jpg'
			},
			{
				width: 2000,
				height: 1135,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_2000w_1135h.jpg'
			},
			{
				width: 2048,
				height: 1163,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Broomball_2048w_1163h.jpg'
			}
		]
	},
	Instagram: {
		ext: 'png',
		sizes: [
			{
				width: 100,
				height: 100,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Instagram_100w_100h.png'
			},
			{
				width: 200,
				height: 200,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Instagram_200w_200h.png'
			},
			{
				width: 300,
				height: 300,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Instagram_300w_300h.png'
			},
			{
				width: 352,
				height: 352,
				url: 'https://storage.googleapis.com/dukeapo-static-images/Instagram_352w_352h.png'
			}
		]
	}
};
export default ImagesMeta;